# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.felink.com:3000/felink-iOS/FLSpecs.git'

platform :ios, '10.0'

target 'GPUImageDemo' do
#	pod 'GPUImage', '~> 0.1.7'
  pod 'Masonry'
#  pod 'WRNavigationBar','~>1.2.0’
  
  pod 'FDFullscreenPopGesture'
  pod "FLUtility"
end

