# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#source 'http://git.felink.com:3000/felink-iOS/FLSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

def import_pods
  pod 'SDWebImage', '~>3.7.5'
end

target 'UICollectionViewDemo' do
  import_pods
  pod 'AFNetworking', '~>3.0'
  pod 'YYModel', '~> 1.0.4'
end

