# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#source 'http://git.felink.com:3000/felink-iOS/FLSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'CoreAnimationDemo' do
	pod 'pop', '~> 1.0'
	pod 'GBDeviceInfo', '~> 4.2'
	pod 'YYModel', '~> 1.0.4'
	pod 'YYCategories', '~> 1.0.4'
	pod 'MBProgressHUD', '~> 1.0.0'
end

